// Script assets have changed for v2.3.0 see
// https://help.yoyogames.com/hc/en-us/articles/360005277377 for more information
function DeleteButtons(){
	global.option_buttons = []
	global.challenge_buttons = []
	instance_destroy(objOptionCursor)
	instance_destroy(objAttack)
	instance_destroy(objBegin)
	instance_destroy(objButton2)
	instance_destroy(objButton3)
	instance_destroy(objButton4)
	instance_destroy(objCancel)
	instance_destroy(objCombat)
	instance_destroy(objConfirm)
	instance_destroy(objDefend)
	instance_destroy(objDjinni)
	instance_destroy(objItem)
	instance_destroy(objLibrary)
	instance_destroy(objNextTurn)
	instance_destroy(objPsynergy)
	instance_destroy(objDebugDraw)
	instance_destroy(objSummon)
	instance_destroy(objLoadGame)
	instance_destroy(objButton5)
	instance_destroy(objButton6)
	instance_destroy(objButton7)
	instance_destroy(objButton8)
	instance_destroy(objReroll)
	instance_destroy(objTownButton)
	instance_destroy(objShopButton)
	instance_destroy(objContinue)
	instance_destroy(objReturn)
	instance_destroy(objChallenge)
	instance_destroy(objFaceButton1)
	instance_destroy(objFaceButton2)
	instance_destroy(objFaceButton3)
	instance_destroy(objFaceButton4)
}